#cloud-config
packages:
  - git
  - avahi
  - nss-mdns
  - wget
  - squid
  - libsss_autofs
  - cvmfs
  - cvmfs-config-default
  - cvmfs-auto-setup
  - nfs-utils

runcmd:
  # - yum update -y
  # Squid
  - systemctl start squid
  - systemctl enable squid
  # mDNS
  - systemctl start avahi-daemon
  - systemctl enable avahi-daemon
  # CVMFS
  - rpm --import https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
  - rpm -U https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/Packages/cvmfs-config-computecanada-latest.noarch.rpm
  - systemctl restart autofs
  # Shared folders
  - mkdir /project
  - mkdir /scratch
  # NFS
  - systemctl enable rpcbind
  - systemctl enable nfs-server
  # - systemctl enable nfs-lock
  # - systemctl enable nfs-idmap
  - systemctl start rpcbind
  - systemctl start nfs-server
  # - systemctl start nfs-lock
  # - systemctl start nfs-idmap
  # - reboot -n

yum_repos:
    epel:
        baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux
    cvmfs:
        name: CernVM packages
        baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
        gpgcheck: false
        enabled: true
        protect: true

write_files:
  - content: |
      /home     10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
      /project  10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
      /scratch  10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
    path: /etc/exports
  - content: |
        if [[ $UID -ne 0 ]]; then
          if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
            source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
          fi
        fi
    path: /etc/profile.d/z-00-computecanada.sh
  - content: |
        CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca"
        CVMFS_QUOTA_LIMIT=4450
        CVMFS_HTTP_PROXY="http://localhost:3128"
    path: /etc/cvmfs/default.local
  - content: |
        acl manager proto cache_object
        acl localhost src 127.0.0.1/32 ::1
        acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
        acl SSL_ports port 443
        acl Safe_ports port 80
        acl Safe_ports port 443
        acl Safe_ports port 1025-65535
        acl CONNECT method CONNECT

        # predefined http_accesses
        http_access allow manager localhost
        http_access deny manager
        http_access deny !Safe_ports
        http_access deny CONNECT !SSL_ports

        # user-defined ACLs
        acl compute_network src 10.0.0.0/16
        acl compute_dstdom_regex dstdom_regex ^(cvmfs-.*\.computecanada\.ca)$

        # user-defined http_accesses
        http_access allow compute_network compute_dstdom_regex
        http_access allow localhost
        http_access deny all

        # user-defined http_port
        http_port 3128

        # general settings
        coredump_dir                   /var/spool/squid
        maximum_object_size_in_memory  512 KB
        maximum_object_size            4096 KB
        ignore_expect_100              off
        cache_mgr                      root
        client_persistent_connections  on
        server_persistent_connections  on
        forwarded_for                  on
        via                            on
        access_log                     /var/log/squid/access.log

        cache_mem                      256 MB
        cache_store_log                /var/log/squid/store.log
        cache_log                      /var/log/squid/cache.log

        refresh_pattern /cvmfs/soft.computecanada.ca/.cvmfs*          	0  100%	30
        refresh_pattern /cvmfs/soft.computecanada.ca/data/*   	525600  100%	525600 
        refresh_pattern                .                     0    20%     4320

        cache_dir ufs /var/spool/squid 4096 16 256
    path: /etc/squid/squid.conf