#cloud-config
packages:
  - git
  - avahi
  - avahi-tools
  - nss-mdns
  - wget
  - squid
  - libsss_autofs
  - cvmfs
  - cvmfs-config-default
  - cvmfs-auto-setup
  - nfs-utils
  - mariadb-server

runcmd:
  # - yum update   -y
  # Squid
  - systemctl start squid
  - systemctl enable squid
  # mDNS
  - systemctl start avahi-daemon
  - systemctl enable avahi-daemon
  # CVMFS
  - rpm --import https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
  - rpm -U https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/Packages/cvmfs-config-computecanada-latest.noarch.rpm
  - systemctl restart autofs
  # Shared folders
  - mkdir /project
  - mkdir /scratch
  # NFS
  - systemctl enable rpcbind
  - systemctl enable nfs-server
  - systemctl start rpcbind
  - systemctl start nfs-server
  # Slurm
  - groupadd -g 2001 slurm
  - useradd -m -c "Slurm workload manager" -d /var/lib/slurm -u 2001 -g slurm  -s /bin/bash slurm
  - groupadd -g 2002 munge
  - useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u 2002 -g munge  -s /sbin/nologin munge
  - yum install -y munge munge-libs
  - mkdir /var/spool/slurm
  - chown slurm:slurm /var/spool/slurm
  - chown slurm:slurm /etc/slurm/slurm.conf
  - chown munge:munge /etc/munge/munge.key
  - systemctl enable munge
  - systemctl start  munge
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-17.11.5-1.el7.centos.x86_64.rpm
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-perlapi-17.11.5-1.el7.centos.x86_64.rpm
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-plugins-17.11.5-1.el7.centos.x86_64.rpm
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-slurmdbd-17.11.5-1.el7.centos.x86_64.rpm
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-slurmctld-17.11.5-1.el7.centos.x86_64.rpm
  # Find hostnames
  # - avahi-browse -atpr | awk -F';' '{print $8, $7}' | sed '/^ *$/d' | sed 's/.local//' >> /etc/hosts

yum_repos:
    epel:
        baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux
    cvmfs:
        name: CernVM packages
        baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
        gpgcheck: false
        enabled: true
        protect: true

write_files:
  - content: |
        # MANAGEMENT POLICIES
        ControlMachine=login1
        AuthType=auth/munge
        CryptoType=crypto/munge
        SlurmUser=slurm

        # NODE CONFIGURATIONS
        NodeName=compute-node[1-${nb_nodes}]

        # PARTITION CONFIGURATIONS
        PartitionName=debug Nodes=compute-node[1-${nb_nodes}] Default=YES

        SlurmctldPort=6817
        SlurmdPort=6818

        SlurmctldDebug=debug
        SlurmctldLogFile=/var/log/slurmctld.log
        SlurmdDebug=debug
        SlurmdLogFile=/var/log/slurmd.log

        SlurmctldPidFile=/var/run/slurmctld.pid
        SlurmdPidFile=/var/run/slurmd.pid

        StateSaveLocation=/var/spool/slurm
    path: /etc/slurm/slurm.conf
  - content: |
        VkJmEF/j97xr7L33ZYsf/mZdQ527MxyvVkoBSL8H9fCjeKtrDTPJBHecsO4/iTvO
        hrOxJBh0hsLZjyl8w7V8hZISKKMyqebNL2cknn/cj7l4zbt+E3lb+RRYlfCkGHgB
        lXw86SzhFLJRjKwHTKSrhgIeFVsHXasAzakYIxJecZ7GpiwK6ViSR1hj4j06fNqC
        Wb+v3nkZGBc5HpjuxOViHr6em/z++p9b2MYGPBrZwN40ZtLtWlUWwVR/BlIiHalr
        xDC2bqMz9ubJYbAgfE/NimwsLyqQN/2kuFplBmzSNP11EZSGKFo8DM1KNFmteotG
        zanfP6uBJvgSdw3FtctsxEX06Ch6jLuGDdW6WhWJN+eH+aghEKANExdQdJtaiCr1
        HgY3xNFJzVVZcUHozWRP9GzbXdZ5SzdcQYTfZmyMcxIKRvKFLxtWTwpFfhmAPaei
        j8PlTMgZQWoVtSOpSqD3/ngUGItvs1ofqEW2eit4q+/1nKkL3M7HsorEkd2UiVN4
        g2w/m+fct72XdEp+dSRCGxNkvHpMssMg4HdgTp5EfNXRTCnWk3JOdo+0bT3L9GJc
        DnklNqvGBRVu6Fw+QBt2C7yHg+PCcJ0PNUqkuoT3k5VQibAu1w0gp/WmqG3gJhwe
        1/EXOmkL8Ml060P8nSmt6yYhzihn3s90wHMvdJQa3CnlwPFd/iw80F9cBybqjtKo
        Ck5M0nycCcprXteIOqR1ysy8KyCG6rCafk02VdW9wgY1ZthLCHdjzKrzuyzuybac
        gfa/jFpFKmmTCWsrkYcbxFx9JL1J+ZKpqHJMM9gv+4x0fn4CTnOFMgVHibmXNYqH
        lqLxR9+Sg2Ny9w2xd+13KaWii/FtmD2Pgp/P5XGPwSPT4WtzA853MeESBPqmFwlu
        6tSDtez8yQKR+zj3FzPx+EVw41VNzNt+dm6bWGz4pvS4QqUr329xygeOqJjVV4BX
        TnPuU7yPGYOKLu5cazqhKH0vV9tGKHXb+dxJ3ji/tPR85Nsr6vQ72RRqscroa3Fq
        BP11zaizzi+uf5Zf/VTyFx/04r2rbdmhU/lFFAdpmEhLfrgQzkAJHT+w+xzd1hp6
        +f9fjG15HiDM8rhkDkSZovK4c9tI+LKv3TrrH77ZG/ufvFPfm6u8iR95xRMh9kWG
        FfPW4jZl0HkQQlr8uv/gItnt4H9DZjpkOAteb/Z2y/ahPEzQkddpct5D/JjHSI40
        0J/dvVhHs9hhiSsn9PLNSRfa7psxAZNde8JrbKeU6ntI0C/GYpz8zyWillKXZ55g
        EmeBi8LpnS+OuHq9BmWqLYdmr5zcZHPlJ8XycPQE7g82h9f0LOKfe0YVeqxVo+T7
        Kraf+lA9U1nDEKob6RLYyw==
    path: /etc/munge/munge.key
    permissions: "0400"
    encoding: "base64"
  - content: |
        /home     10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
        /project  10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
        /scratch  10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)
    path: /etc/exports        
  - content: |
        if [[ $UID -ne 0 ]]; then
          if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
            source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
          fi
        fi
    path: /etc/profile.d/z-00-computecanada.sh        
  - content: |
        CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca"
        CVMFS_QUOTA_LIMIT=4450
        CVMFS_HTTP_PROXY="http://localhost:3128"
    path: /etc/cvmfs/default.local
  - content: |
        acl manager proto cache_object
        acl localhost src 127.0.0.1/32 ::1
        acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
        acl SSL_ports port 443
        acl Safe_ports port 80
        acl Safe_ports port 443
        acl Safe_ports port 1025-65535
        acl CONNECT method CONNECT

        # predefined http_accesses
        http_access allow manager localhost
        http_access deny manager
        http_access deny !Safe_ports
        http_access deny CONNECT !SSL_ports

        # user-defined ACLs
        acl compute_network src 10.0.0.0/16
        acl compute_dstdom_regex dstdom_regex ^(cvmfs-.*\.computecanada\.ca)$

        # user-defined http_accesses
        http_access allow compute_network compute_dstdom_regex
        http_access allow localhost
        http_access deny all

        # user-defined http_port
        http_port 3128

        # general settings
        coredump_dir                   /var/spool/squid
        maximum_object_size_in_memory  512 KB
        maximum_object_size            4096 KB
        ignore_expect_100              off
        cache_mgr                      root
        client_persistent_connections  on
        server_persistent_connections  on
        forwarded_for                  on
        via                            on
        access_log                     /var/log/squid/access.log

        cache_mem                      256 MB
        cache_store_log                /var/log/squid/store.log
        cache_log                      /var/log/squid/cache.log

        refresh_pattern /cvmfs/soft.computecanada.ca/.cvmfs*          	0  100%	30
        refresh_pattern /cvmfs/soft.computecanada.ca/data/*   	525600  100%	525600 
        refresh_pattern                .                     0    20%     4320

        cache_dir ufs /var/spool/squid 4096 16 256
    path: /etc/squid/squid.conf
