#cloud-config
packages:
  - git
  - avahi
  - nss-mdns
  - wget
  - libsss_autofs
  - cvmfs
  - cvmfs-config-default
  - cvmfs-auto-setup
  - nfs-utils

runcmd:
  # - yum update -y
  - mkdir -p /mnt/nfs/home
  - mkdir -p /mnt/nfs/project /project
  - mkdir -p /mnt/nfs/scratch /scratch
  - systemctl start avahi-daemon
  - systemctl enable avahi-daemon
  - rpm --import https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
  - rpm -U https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/Packages/cvmfs-config-computecanada-latest.noarch.rpm
  - systemctl restart autofs
  # - reboot -n

yum_repos:
    epel:
        baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux
    cvmfs:
        name: CernVM packages
        baseurl: http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
        gpgcheck: false
        enabled: true
        protect: true

write_files:
  - content: |
        if [[ $UID -ne 0 ]]; then
          if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
            source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
          fi
        fi
    path: /etc/profile.d/z-00-computecanada.sh
  - content: |
        CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca"
        CVMFS_QUOTA_LIMIT=4450
        CVMFS_HTTP_PROXY="http://${login1_ip}:3128"
    path: /etc/cvmfs/default.local

mounts:
  - ["${login1_ip}:/home", "/mnt/nfs/home", "nfs", "auto,nofail,noatime,nolock,intr,tcp,actimeo=1800", "0", "0"]
  - ["${login1_ip}:/project", "/mnt/nfs/project", "nfs", "auto,nofail,noatime,nolock,intr,tcp,actimeo=1800", "0", "0"]
  - ["${login1_ip}:/scratch", "/mnt/nfs/scratch", "nfs", "auto,nofail,noatime,nolock,intr,tcp,actimeo=1800", "0", "0"]
  - ["/mnt/nfs/home", "/home", "none", "default,bind", "0", "0"]
  - ["/mnt/nfs/project", "/project", "none", "default,bind", "0", "0"]
  - ["/mnt/nfs/scratch", "/scratch", "none", "default,bind", "0", "0"]
