#cloud-config
packages:
  - vim
  - unzip
  - rsyslog

package_reboot_if_required: true

runcmd:
  - bash /root/addswap.sh
  - bash /root/disable_firewalld.sh
  # Slurm
  - groupadd -g 2001 slurm
  - useradd -m -c "Slurm workload manager" -d /var/lib/slurm -u 2001 -g slurm  -s /bin/bash slurm
  - groupadd -g 2002 munge
  - useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u 2002 -g munge  -s /sbin/nologin munge
  - yum install -y munge munge-libs
  - mkdir /var/spool/slurm
  - chown slurm:slurm /var/spool/slurm
  - chown slurm:slurm /etc/slurm
  - chown slurm:slurm /etc/slurm/slurm.conf
  - chown slurm:slurm /etc/slurm/plugstack.conf
  - chown munge:munge /etc/munge/munge.key
  - systemctl enable munge
  - systemctl start  munge
  - yum install -y slurm
  - curl https://gist.github.com/cmd-ntrf/a9305513809e7c9a104f79f0f15ec067/raw/da71a07f455206e21054f019d26a277daeaa0f00/cc-tmpfs_mounts.so --output /usr/lib64/slurm/cc-tmpfs_mounts.so --silent
  # Free IPA
  - bash /root/freeipa.sh

yum_repos:
    darrenboss-slurm:
        name: Copr repo for Slurm owned by darrenboss
        baseurl: https://copr-be.cloud.fedoraproject.org/results/darrenboss/Slurm/epel-7-$basearch/
        type: rpm-md
        skip_if_unavailable: True
        gpgcheck: 1
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/darrenboss/Slurm/pubkey.gpg
        repo_gpgcheck: 0
        enabled: 1
        enabled_metadata: 1
    epel:
        baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux
    elrepo:
        name: ELRepo.org Community Enterprise Linux Repository - el7
        baseurl: http://muug.ca/mirror/elrepo/elrepo/el7/$basearch/
        enabled: true
        gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
        protect: false


write_files:
  - path: /var/run/reboot-required
    permissions: 644
  - path: /root/disable_firewalld.sh
    permissions: 0700
    content: |
        #!/bin/bash
        cat > /etc/sysconfig/iptables << END
        *filter
        :INPUT ACCEPT [0:0]
        :FORWARD ACCEPT [0:0]
        :OUTPUT ACCEPT [0:0]
        -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
        -A INPUT -p icmp -j ACCEPT
        -A INPUT -i lo -j ACCEPT
        COMMIT
        END

        systemctl stop firewalld && systemctl start iptables; systemctl start ip6tables
        systemctl disable firewalld
        systemctl mask firewalld
        systemctl enable iptables
        systemctl enable ip6tables
  - path: /root/addswap.sh
    permissions: 0700
    content: |
        #!/bin/bash
        set -e
        dd if=/dev/zero of=/swapfile bs=1M count=1024
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        echo "/swapfile none swap defaults 0 0" >> /etc/fstab
  - content: |
        # MANAGEMENT POLICIES
        ClusterName=${cluster_name}
        ControlMachine=mgmt01
        AuthType=auth/munge
        CryptoType=crypto/munge
        SlurmUser=slurm

        # SCHEDULER CONFIGURATIONS
        SchedulerType=sched/backfill
        SelectType=select/cons_res
        SelectTypeParameters=CR_Core_Memory

        # NODE CONFIGURATIONS
        NodeName=node[1-100] State=FUTURE

        # PARTITION CONFIGURATIONS
        PartitionName=cpubase_bycore_b1 Nodes=ALL Default=YES

        SlurmctldPort=6817
        SlurmdPort=6818

        SlurmctldDebug=debug
        SlurmctldLogFile=/var/log/slurmctld.log
        SlurmdDebug=debug
        SlurmdLogFile=/var/log/slurmd.log

        SlurmctldPidFile=/var/run/slurmctld.pid
        SlurmdPidFile=/var/run/slurmd.pid

        # JOBS AND TASKS/RESOURCES CONTROL
        TmpFS=/localscratch
        # Prolog=/etc/slurm/prolog
        Epilog=/etc/slurm/epilog
        MpiDefault=pmi2
        ProctrackType=proctrack/cgroup
        TaskPlugin=task/cgroup

        StateSaveLocation=/var/spool/slurm
        SallocDefaultCommand=\"srun -n1 -N1 --mem-per-cpu=0 --pty --preserve-env --mpi=none bash\"

    path: /etc/slurm/slurm.conf
  - path: /etc/slurm/cgroup.conf
    content: |
        CgroupMountpoint=/cgroup
        CgroupAutomount=yes
        ConstrainCores=yes
        #ConstrainRAMSpace=yes
        AllowedRAMSpace=98.5
  - path: /etc/slurm/plugstack.conf
    content: |
        # SLURM plugin stack config file for "cc-tmpfs_mounts"
        #
        # required/optional    plugin                arguments
        #
        # Options are list of directories you want to remount as tmpfs for the user: tmpfs=/tmp tmpfs=/var/tmp
        #
        ## This one Breaks MPI Jobs
        # required /usr/lib64/slurm/cc-tmpfs_mounts.so tmpfs=/tmp tmpfs=/dev/shm target=/localscratch bind=/var/tmp/
        ## Remounted 50% size tmpfs
        # required /usr/lib64/slurm/cc-tmpfs_mounts.so tmpfs=/tmp bindself=/dev/shm target=/localscratch bind=/var/tmp/
        ## Better option, bindmount to an already mounted /tmp which inherits its size setting
        required /usr/lib64/slurm/cc-tmpfs_mounts.so bindself=/tmp bindself=/dev/shm target=/localscratch bind=/var/tmp/
  - path: /etc/slurm/epilog
    permissions: 0755
    content: |
        #!/bin/bash
        rm -rf "/localscratch/$SLURM_JOB_USER.$SLURM_JOBID.0"
        rm -rf "/dev/shm/$SLURM_JOB_USER.$SLURM_JOBID.0"
        rm -rf "/tmp/$SLURM_JOB_USER.$SLURM_JOBID.0"
        exit 0
  - content: |
        VkJmEF/j97xr7L33ZYsf/mZdQ527MxyvVkoBSL8H9fCjeKtrDTPJBHecsO4/iTvO
        hrOxJBh0hsLZjyl8w7V8hZISKKMyqebNL2cknn/cj7l4zbt+E3lb+RRYlfCkGHgB
        lXw86SzhFLJRjKwHTKSrhgIeFVsHXasAzakYIxJecZ7GpiwK6ViSR1hj4j06fNqC
        Wb+v3nkZGBc5HpjuxOViHr6em/z++p9b2MYGPBrZwN40ZtLtWlUWwVR/BlIiHalr
        xDC2bqMz9ubJYbAgfE/NimwsLyqQN/2kuFplBmzSNP11EZSGKFo8DM1KNFmteotG
        zanfP6uBJvgSdw3FtctsxEX06Ch6jLuGDdW6WhWJN+eH+aghEKANExdQdJtaiCr1
        HgY3xNFJzVVZcUHozWRP9GzbXdZ5SzdcQYTfZmyMcxIKRvKFLxtWTwpFfhmAPaei
        j8PlTMgZQWoVtSOpSqD3/ngUGItvs1ofqEW2eit4q+/1nKkL3M7HsorEkd2UiVN4
        g2w/m+fct72XdEp+dSRCGxNkvHpMssMg4HdgTp5EfNXRTCnWk3JOdo+0bT3L9GJc
        DnklNqvGBRVu6Fw+QBt2C7yHg+PCcJ0PNUqkuoT3k5VQibAu1w0gp/WmqG3gJhwe
        1/EXOmkL8Ml060P8nSmt6yYhzihn3s90wHMvdJQa3CnlwPFd/iw80F9cBybqjtKo
        Ck5M0nycCcprXteIOqR1ysy8KyCG6rCafk02VdW9wgY1ZthLCHdjzKrzuyzuybac
        gfa/jFpFKmmTCWsrkYcbxFx9JL1J+ZKpqHJMM9gv+4x0fn4CTnOFMgVHibmXNYqH
        lqLxR9+Sg2Ny9w2xd+13KaWii/FtmD2Pgp/P5XGPwSPT4WtzA853MeESBPqmFwlu
        6tSDtez8yQKR+zj3FzPx+EVw41VNzNt+dm6bWGz4pvS4QqUr329xygeOqJjVV4BX
        TnPuU7yPGYOKLu5cazqhKH0vV9tGKHXb+dxJ3ji/tPR85Nsr6vQ72RRqscroa3Fq
        BP11zaizzi+uf5Zf/VTyFx/04r2rbdmhU/lFFAdpmEhLfrgQzkAJHT+w+xzd1hp6
        +f9fjG15HiDM8rhkDkSZovK4c9tI+LKv3TrrH77ZG/ufvFPfm6u8iR95xRMh9kWG
        FfPW4jZl0HkQQlr8uv/gItnt4H9DZjpkOAteb/Z2y/ahPEzQkddpct5D/JjHSI40
        0J/dvVhHs9hhiSsn9PLNSRfa7psxAZNde8JrbKeU6ntI0C/GYpz8zyWillKXZ55g
        EmeBi8LpnS+OuHq9BmWqLYdmr5zcZHPlJ8XycPQE7g82h9f0LOKfe0YVeqxVo+T7
        Kraf+lA9U1nDEKob6RLYyw==
    path: /etc/munge/munge.key
    permissions: "0400"
    encoding: "base64"

disable_ec2_metadata: false
timezone: "America/Montreal"
output: { all: "| tee -a /var/log/cloud-init-output.log" }
