#cloud-config

mounts:
  - [ ${home_dev}1, /mnt/home, nofail]
  - [ ${project_dev}1, /project, nofail]
  - [ ${scratch_dev}1, /scratch, nofail]

runcmd:
  - parted -s ${home_dev} mklabel gpt
  - parted -s ${project_dev} mklabel gpt
  - parted -s ${scratch_dev} mklabel gpt
  - parted -s -a opt ${home_dev} mkpart primary ext4 0% 100%
  - parted -s -a opt ${project_dev} mkpart primary ext4 0% 100%
  - parted -s -a opt ${scratch_dev} mkpart primary ext4 0% 100%
  - mkfs.xfs -L home ${home_dev}1
  - mkfs.xfs -L project ${project_dev}1
  - mkfs.xfs -L scratch ${scratch_dev}1
  - mkdir -p /mnt/home
  - mkdir -p /project
  - mkdir -p /scratch
  - mount -L home /mnt/home
  - 'test ! -d /mnt/home/centos && cp -rp /home/centos /mnt/home/centos'
  - mount -L project /project
  - mount -L scratch /scratch
