#cloud-config

runcmd:
  - parted -s "${home_dev}" mklabel gpt
  - parted -s "${project_dev}" mklabel gpt
  - parted -s "${scratch_dev}" mklabel gpt
  - parted -s -a opt "${home_dev}" mkpart primary ext4 0% 100%
  - parted -s -a opt "${project_dev}" mkpart primary ext4 0% 100%
  - parted -s -a opt "${scratch_dev}" mkpart primary ext4 0% 100%
  - mkfs.ext4 -L home "${home_dev}"1
  - mkfs.ext4 -L project "${project_dev}"1
  - mkfs.ext4 -L scratch "${scratch_dev}"1
  - mkdir -p /mnt/home
  - mkdir -p /mnt/project
  - mkdir -p /mnt/scratch
  - mount -L home /mnt/home
  - mount -L project /mnt/project
  - mount -L scratch /mnt/scratch
  - usermod -d /mnt/home/centos centos
  - mv /home/centos /mnt/home/centos
