packages:
  - ipa-client
  - libsss_autofs
  - cvmfs
  - cvmfs-config-default
  - cvmfs-auto-setup
  - nfs-utils
  - python36  
  - git

runcmd:
  # NFS
  - setsebool -P use_nfs_home_dirs 1
  - mkdir -p /project /scratch
  - echo "mgmt01:/home      /home      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/project   /project   nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/scratch   /scratch   nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/etc/slurm /etc/slurm nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # CVMFS
  - rpm --import https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
  - rpm -U https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/Packages/cvmfs-config-computecanada-latest.noarch.rpm
  - systemctl restart autofs
  # slurmd
  - bash /root/update_slurm.sh
  - yum install -y https://git.computecanada.ca/fafor10/slurm_rpms/raw/master/17.11.5/slurm-slurmd-17.11.5-1.el7.centos.x86_64.rpm
  - systemctl enable slurmd
  - systemctl start  slurmd

write_files:
  - content: |
        #!/bin/bash
        if [[ "${hostname}" == "node1"  ]]; then
            RAM=$(free -m  | grep Mem | awk '{print $2}')
            SOCKETS=$(grep processor /proc/cpuinfo | wc -l)
            STRING="Sockets=$SOCKETS CoresPerSocket=1 ThreadsPerCore=1 RealMemory=$RAM"
            sed -i "/^NodeName/ s/\$/ $STRING/" /etc/slurm/slurm.conf
            scontrol reconfigure
        fi
    path: /root/update_slurm.sh
  - content: |
        if [[ $UID -ne 0 ]]; then
          if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
            source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
          fi
        fi
    path: /etc/profile.d/z-00-computecanada.sh
  - path: /root/freeipa.sh
    permissions: 0700
    content: |
        #!/bin/bash
        DOMAIN=$(grep search /etc/resolv.conf | awk '{print $2}')
        hostnamectl set-hostname ${hostname}.$DOMAIN
        sed -i "/nameserver/c\nameserver ${mgmt01_ip}" /etc/resolv.conf
        chattr +i /etc/resolv.conf
        until ping -c1 mgmt01 &>/dev/null; do :; done
        sleep 30
        ipa-client-install --mkhomedir --ssh-trust-dns \
                           --enable-dns-updates \
                           --unattended -p admin \
                           -w ${admin_passwd}
  - path: /etc/cvmfs/default.local
    content: |
        CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca"
        CVMFS_QUOTA_LIMIT=4450
        CVMFS_HTTP_PROXY="http://mgmt01:3128"
