#cloud-config
packages:
  - git

runcmd:
  - rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
  - yum -y install puppet-agent
  - /opt/puppetlabs/puppet/bin/gem install librarian-puppet
  - "(cd /etc/puppetlabs/puppet && HOME=/root PATH=$PATH:/opt/puppetlabs/puppet/bin /opt/puppetlabs/puppet/bin/librarian-puppet install)"
  - /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/puppet/site.pp --color=false --logdest /var/log/puppetlabs/puppet/puppet.log
  - crontab /root/crontab
  # - reboot -n

write_files:
  - content: |
      @reboot /usr/bin/flock -n /var/lock/puppet.lock /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/puppet/site.pp --color=false --logdest /var/log/puppetlabs/puppet/puppet.log
      */5 * * * * /usr/bin/flock -n /var/lock/puppet.lock /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/puppet/site.pp --color=false --logdest /var/log/puppetlabs/puppet/puppet.log
    path: /root/crontab
  - content: |
      ${puppetfile}
    path: /etc/puppetlabs/puppet/Puppetfile
  - content: |
      ${site_pp}
    path: /etc/puppetlabs/puppet/site.pp
  - content: |
      ${data}
    path: /etc/puppetlabs/puppet/hieradata/data.yaml
    owner: root:root
    permissions: "0600"
  - content: |
      [main]
      codedir=$confdir
      environmentpath=$confdir
      environment=''
    path: /etc/puppetlabs/puppet/puppet.conf
  - content: |
      ---
      version: 5
      defaults:
        datadir: /etc/puppetlabs/puppet/hieradata
        data_hash: yaml_data
      hierarchy:
        - name: "Data"
          path: "data.yaml"
    path: /etc/puppetlabs/puppet/hiera.yaml

disable_ec2_metadata: false
timezone: "America/Montreal"
fqdn: "${node_name}"
output: { all: "| tee -a /var/log/cloud-init-output.log" }
