name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    env:
      TF_VERSION: 0.14.7

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Retrieve tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Cache Terraform
        id: cache-terraform
        uses: actions/cache@v2
        with:
          path: ~/bin
          key: terraform-${{ env.TF_VERSION }}

      - name: Download terraform
        if: steps.cache-terraform.outputs.cache-hit != 'true'
        run: |
          mkdir -p "${HOME}/bin"
          curl -sSL -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
          unzip terraform.zip
          mv -v terraform "${HOME}/bin/terraform"
          ~/bin/terraform version

      - name: Create tarballs and zips
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export PATH=~/bin:$PATH
          ./release.sh $(git describe --tags --abbrev=0)

      - name: Generate Changelog
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          sed -n "/^## \[${SOURCE_TAG}\]/,/^## \[/p" CHANGELOG | sed '1d;2d;$d' | sed '$d' | sed 's/###/##/' > ${SOURCE_TAG}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Magic Castle ${{ steps.tag_name.outputs.SOURCE_TAG }}
          body_path: ${{ steps.tag_name.outputs.SOURCE_TAG }}-CHANGELOG.txt
          draft: true
          files: |
            releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
