name: Validate Terraform code

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test_cloud_provider:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ['aws', 'azure', 'gcp', 'openstack', 'ovh']
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Create SSH keys
        run: ssh-keygen -b 2048 -t rsa -q -N "" -f ~/.ssh/id_rsa
      - name: Test ${{ matrix.provider }}
        uses: ./.github/actions/test_provider
        with:
          provider: ${{ matrix.provider }}
  test_dns_provider:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ['cloudflare', 'gcloud', 'txt']
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Init ${{ matrix.provider }} DNS
        run: terraform -chdir=dns/${{ matrix.provider }} init
      - name: Validate ${{ matrix.provider }} DNS
        run: terraform -chdir=dns/${{ matrix.provider }} validate
  trivy-vuln-scan:
    name: Running Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve symbolic links and fix source
        run: |
          rm {aws,azure,gcp,openstack}/{outputs.tf,variables.tf}
          for cloud in aws azure gcp openstack; do
            cp common/outputs.tf common/variables.tf $cloud/;
          done
          for example in examples/*/*.tf; do
            sed -i 's;git::https://github.com/ComputeCanada/magic_castle.git//;../../;g' $example
          done

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.61.1
          cache: true

      - name: Run Trivy on providers
        run: trivy config --misconfig-scanners terraform --tf-exclude-downloaded-modules --skip-dirs examples/advanced --format json -o trivy-results.json .

      - name: Convert Trivy JSON output to SARIF and filter duplicated results
        run: |
          trivy convert --format sarif trivy-results.json --output trivy-results.sarif
          # When converting from JSON to SARIF, some information, like origin of the misconfiguration, is lost.
          # The lost information results in duplicated issues. We filter these issues with jq and create a new
          # sarif file that will be uploaded to the security tab.
          jq 'reduce .runs[0].results[] as $a ([]; if IN(.[]; $a) then . else . += [$a] end)' trivy-results.sarif > trivy-results-filtered.sarif
          jq ".runs[0].results |= $(cat trivy-results-filtered.sarif)" trivy-results.sarif > trivy-results-final.sarif
          mv trivy-results-final.sarif trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy-results.json ]]; then
          {
            echo "### Trivy Misconfiguration Scan Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```console'
            echo '$ trivy config --misconfig-scanners terraform --tf-exclude-downloaded-modules --skip-dirs examples/advanced .'
            trivy convert --format table trivy-results.json
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
          fi
